config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'hellos#index'
  resources :posts
  post '/hellos/guest_sign_in', to: 'hellos#guest_sign_in'
  resources :calendars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
# frozen_string_literal: true

class Calendar < ApplicationRecord
  validates :title, length: { maximum: 50 }, presence: true
  validates :memo, length: { maximum: 500 }, presence: true

  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :title, length: { maximum: 50 }, presence: true
  validates :contents, length: { maximum: 500 }, presence: true
  validates :tag, length: { maximum: 10 }, presence: true
  validates :time, numericality: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :calendars
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/calendars_controller.rb
# frozen_string_literal: true

class CalendarsController < ApplicationController
  before_action :set_calendar, only: %i[show edit update destroy]

  # GET /calendars or /calendars.json
  def index
    @calendars = current_user.calendars
  end

  # GET /calendars/1 or /calendars/1.json
  def show; end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit; end

  # POST /calendars or /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)
    @calendar.user = current_user

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'メモしました。' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1 or /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: '更新しました。' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1 or /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'メモを削除しました' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_calendar
    @calendar = Calendar.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def calendar_params
    params.require(:calendar).permit(:title, :memo, :start_time)
  end
end

app/controllers/hellos_controller.rb
# frozen_string_literal: true

class HellosController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @q = current_user.posts.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page]).per(7)
    @post = current_user.posts.sum(:time)
    

  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '無事記録できました' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '無事に更新できました' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '無事に削除できました' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :contents, :time, :tag)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/calendars_helper.rb
# frozen_string_literal: true

module CalendarsHelper
end

app/helpers/hellos_helper.rb
# frozen_string_literal: true

module HellosHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/calendars/_form.html.erb
<%= form_with(model: calendar, local: true) do |form| %>
  <div class = "d-flex justify-content-center col-12 flex-wrap text-center">
    <% if calendar.errors.any? %>
      <div id="error_explanation">
        <h2>エラーがあります</h2>
  
        <ul>
          <% calendar.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  </div>
    <% end %>
  
  
  <%= form_with(model: @calendar, local: true) do |form| %>
  
    <div class = "field  d-flex justify-content-center col-12 flex-wrap mt-5">
        <%= form.label :title , class: "col-10"%>
      <%= form.text_field :title, class: "form-control col-10"%>
      </div>
  
      <div class="field  d-flex justify-content-center col-12 flex-wrap">
        <%= form.label :memo , class: "col-10"%>
      <%= form.text_field :memo , class: "form-control col-10"%>
      </div>
      
    <div class = "field  col-11 flex-wrap mt-3 text-center">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time , class: "form-control col-10" %>
      </div>
    </div>
  
      <div class="actions field  d-flex justify-content-center col-12 flex-wrap mt-5">
      <%= form.submit "投稿", class: "btn btn-primary col-10 "%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/calendars/edit.html.erb
<%= render 'form', calendar: @calendar %>

app/views/calendars/index.html.erb
<div class="toppage">
  <h1 class="top">カレンダー</h1>
  <div class="text-right mr-5">
    <%= link_to "カレンダー登録", new_calendar_path,class: "button-32"%>
  </div>

  <br>

  <div class="row">
    <div class="col-11 d-flex justify-content-center flex-wrap ml-5 ">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>目標</th>
            <th>日程</th>
          </tr>
        </thead>

        <tbody>
          <% @calendars.each do |calendar| %>
            <tr>
              <td><%= calendar.title%> <%= link_to(calendar) do %>
              <i class="fas fa-search btn btn-primary text-white ml-3 fa-xs"></i>
              <% end %></td>
              <td><%= calendar.start_time.strftime("%m-%d") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <br>
      <div class="col-10 pr-4">

        <%= month_calendar events: @calendars do |date, calendars| %>
          <%= date.day %>
          <% calendars.each do |calendar| %>
            <div>
              <%= link_to calendar.title, calendar %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>

app/views/calendars/new.html.erb
<%= render 'form', calendar: @calendar %>

app/views/calendars/show.html.erb
<div class="show">
  <div class="col-11 d-flex justify-content-end flex-wrap ml-5 mb-4 ">
          <%= link_to edit_calendar_path(@calendar)do %>
          <i class= "fas fa-edit btn btn-secondary text-white fa-3x	"></i>
          <% end %>
            <%= link_to calendar_path(@calendar.id) , class: "ml-3 btn btn-danger text-white",data: {confirm: '本当に削除しますか？'}, method: :delete do %>
      <i class="far fa-trash-alt fa-2x"></i> 
    <% end %>
  </div>
  <div class = "card mb-4">
    <div class= "card-header">
      <h3>目標</h3>
    </div>
    <div class ="card-body">
      <div class ="card-text">
    <%= @calendar.title %>
      </div>
    </div>
  </div>
  
  <div class = "card mb-4">
    <div class= "card-header">
      <h3>日付</h3>
    </div>
    <div class ="card-body">
      <div class ="card-text">
    <%= @calendar.start_time.strftime("%m-%d") %>
      </div>
    </div>
  </div>
  
  <div class = "card mb-4">
    <div class= "card-header">
      <h3>内容</h3>
    </div>
    <div class ="card-body">
      <div class ="card-text">
    <%= @calendar.memo %>
      </div>
    </div>
  </div>
</div>

app/views/hellos/index.html.erb
<div class = "hellos pb-5">
        <div class = "d-flex justify-content-center flex-wrap">
                <h1 class = "col-12 text-center">ようこそ、駆け出しのためのツールへ</h1>
                        <%= image_tag'IMG_0349.jpg', alt: "パソコンに向かう女の子" ,class:'icon mt-5 mr-5'  %>
                        <div class = "mt-5">

                                <% if !user_signed_in?%>
                                <div class = "ml-3">
                                        <h5 class = "mt-5">あなたの勉強をサポートします</h5>
                                        <div class="button-80 ml-5 mt-3 col-6" >
                                        <%= link_to 'ゲストログイン', hellos_guest_sign_in_path, method: :post %>
                                        </div>
                                        <div class="button-80 ml-5 mt-4 col-6" >
                                        <%= link_to 'ログイン', user_session_path, method: :post %>
                                        </div>
                                </div>
                                <%end%>
                        </div>
        </div>
                <div class = "container mb-5">
                                <h2 class = "text-center mt-5 ">特徴</h2>
        
                                <div class = "mt-4 box mb-5 mt-5 ">
                                <h4 class = 'text-center mt-5'>学習した内容と時間を記録、スケジュールを管理するためのアプリケーションです。モチベーションを維持して勉強し習慣化できることを目的としています。</h4>
                                <div class = "text-center">
                                        <%= image_tag'IMG_0351.jpg', alt: "メモをする女の子" ,class:'icon1 '%>
                                </div>
                                </div>
                                <h3 class = "text-center mt-5 ">使い方</h3>

                                <div class = "mt-4 box mb-5  ">
                                        <h5 class = " text-center">01</h5>
                                        <h4 class = 'text-center mt-4'>アプリ内のカレンダーにメモして目標を定めよう。</h4>
                                <div class = "text-center">
                                        <%= image_tag'IMG_0350.jpg', alt: "メモをする女の子" ,class:'icon1 '%>
                                </div>
                                </div>

                                <div class = "mt-4 box mb-5  ">
                                        <h5 class = " text-center">02</h5>
                                        <h4 class = 'text-center mt-4'>1日の勉強内容、時間を記録しよう。（時間は30分から記録可能）<br>※30分は0.5、1時間は1、1時間半は1.5</h4>
                                <div class = "text-center">
                                        <%= image_tag'IMG_0352.jpg', alt: "メモをする女の子" ,class:'icon1 '%>
                                </div>
                                </div>

                                <div class = "mt-4 box  ">
                                        <h5 class = " text-center">03</h5>
                                        <h4 class = 'text-center mt-4'>今までの勉強記録を確認しよう。今までの学習時間はホームの左上に。</h4>
                                <div class = "text-center">
                                        <%= image_tag'IMG_0353.jpg', alt: "メモをする女の子" ,class:'icon1 '%>
                                </div>
                                </div>
                        
                </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "hellos", :media => "all" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body class="bg-light">
<% if user_signed_in? && current_user.id  %>


<nav class="navbar navbar-expand-lg navbar-light bg-secondary fixed-bottom">

  <a class="navbar-brand"><%=link_to"study",posts_path,class: " text-white h2 pr-5 pb-3"%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ">
          <li class="nav-item active">
        <h4 class="nav-link"> <%=link_to"ホーム",posts_path,class: "navbar-brand text-white mb-2 "%><i class="fas fa-home text-white fa-x mt-1 pr-3"></i></h4>
      </li>
      <li class="nav-item active">
        <h4 class="nav-link"><%= link_to "記録する", new_post_path, class: "navbar-brand text-white mb-2"%><i class="fas fa-book-open text-white fa-x  pr-3"></i></h4>
      </li>
      <li class="nav-item">
        <h5 class="nav-link" > <%= link_to "カレンダー", calendars_path, class: "navbar-brand text-white mb-2"%><i class="fas fa-calendar-week text-white fa-x pr-3 "></i></h5>
      </li>
      <li class="nav-item">
        <h5 class="nav-link "><%= link_to "ログアウト", destroy_user_session_path, :method => :delete, class: "nav-link text-white " %></h5>
      </li>
    </ul>
  </div>
</nav>
<%end%>

        <% if flash[:notice] %>
          <div class="alert alert-success" role="alert">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%if flash[:alert]%>
          <div class="alert alert-danger" role="alert">
            <%= flash[:alert]%>
          </div>
        <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class = "d-flex justify-content-center col-12 flex-wrap text-center">
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2>エラーがあります</h2>
  
        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  </div>
  <% end %>
  
  <div class = "field  d-flex justify-content-center col-12 flex-wrap mt-5">
      <%= form.label :title , class: "col-10"%>
      <%= form.text_field :title, class: "form-control col-10"%>
    </div>

    <div class="field  d-flex justify-content-center col-12 flex-wrap">
      <%= form.label :contents , class: " col-10"%>
      <%= form.text_area :contents , class: "form-control col-10"%>
    </div>
    <div class="field  d-flex justify-content-center col-12 flex-wrap">
    <div class="field">
    <%= form.label :tag , class: " col-10"%>
      <%= form.text_field :tag, class: "form-control col-10"%>
  </div>

    
  <div class = "field  d-flex justify-content-center col-12 flex-wrap">
    <%= form.label :time, class: " col-10" %>
    <div class = " col-10">
    <%=form.number_field( :time, in: 0.5..24.0, step: 0.5) %>
    </div>
  </div>

    <div class="actions field  d-flex justify-content-center col-12 flex-wrap mt-5">
    <%= form.submit "投稿", class: "btn btn-primary col-10 "%>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>編集</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h2 class = "col-12 mt-5">合計<%= @post %>時間</h2>
<div class = "d-flex align-items-center justify-content-center flex-wrap col-12 mt-2">
  <h1>記録</h1>
</div>

<%= search_form_for @q, class: 'mb-5' do |f|%>
<div class='d-flex justify-content-end'>
  <div class ='col-sm-4  d-flex justify-content-end'>
    <%= f.search_field :tag_cont, placeholder:'タグ名で検索', class: 'form-control'%>
    <%= f.submit class: 'ml-2 btn btn-outline-primary'%>
  </div>
</div>
<%end%>

<div class = "mt-5 ml-5">

  <table class="table">
    <thead>
      <tr>
        <th scope="col">名前</th>
        <th scope="col">更新日</th>
        <th scope="col">タグ</th>
        <th scope="col">詳細</th>
      </tr>
    </thead>
        <% @posts.each do |post| %>
    <tbody>
      <tr>
        <td class = "col-3 themed-grid-col h5"><%= post.title%></td>
        <td class = "col-3 themed-grid-col h5"><%= post.created_at %></td>
        <td class = "col-3 themed-grid-col h5 "><span class=' bg-info text-white  pb-2 pt-1 rounded '><%= post.tag %></span></td>
        <td class = "col-2 themed-grid-col h5"><%= link_to post do %>
          <i class="fas fa-search btn btn-primary text-white"></i>
            <% end %></td>
      </tr>
    </tbody>
        <%end%>
  </table>

</div>
<div class = "d-flex justify-content-center flex-wrap col-12 mb-5">
    <%= paginate @posts%>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
</div>

app/views/posts/new.html.erb
  <%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="col-11 d-flex justify-content-end flex-wrap ml-5 mb-4 ">
        <%= link_to edit_post_path(@post)do %>
        <i class= "fas fa-edit btn btn-secondary text-white fa-3x	"></i>
        <% end %>
          <%= link_to post_path(@post) , class: "ml-3 btn btn-danger text-white", data: {confirm: '本当に削除しますか？'},method: :delete do %>
    <i class="far fa-trash-alt fa-2x"></i> 
  <% end %>
</div>
<div class = "card mb-4">
  <div class= "card-header">
    <h3>タイトル</h3>
  </div>
  <div class ="card-body">
    <div class ="card-text">
      <%= @post.title %>
    </div>
  </div>
</div>

<div class = "card mb-4">
  <div class= "card-header">
    <h3>勉強時間</h3>
  </div>
  <div class ="card-body">
    <div class ="card-text">
      <%= @post.time %>
    </div>
  </div>
</div>

<div class = "card mb-4">
  <div class= "card-header">
    <h3>日付</h3>
  </div>
  <div class ="card-body">
    <div class ="card-text">
      <%= @post.created_at %>
    </div>
  </div>
</div>

<div class = "card mb-4">
  <div class= "card-header">
    <h3>内容</h3>
  </div>
  <div class ="card-body">
    <div class ="card-text">
      <%= @post.contents %>
    </div>
  </div>
</div>

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>